"""
For the purposes of transforming the .sql files into the format used by dbdiagram.io
"""

import json
import os
import re
import sys

def translate_diagram():
    result = ""
    for file in os.listdir("database/schema"):
        if ".sql" not in file: continue
        with open("database/schema/"+file, "r") as f:
            while line := f.readline():
                line = re.sub(r"CREATE TABLE( IF NOT EXISTS)?","TABLE",line,flags=re.IGNORECASE)
                line = re.sub(r"\(\s*$","{\n",line,flags=re.IGNORECASE)
                line = re.sub(r"^\)","}",line,flags=re.IGNORECASE)
                line = re.sub(r"\s*,","",line,flags=re.IGNORECASE)
                line = re.sub(r"^\s+(?P<col>\w+)\s+(?P<type>[\w\(\)]+)\s*(?P<args>.*)\s*",r"\t\1\t\2\t[\3]\n",line,flags=re.IGNORECASE)
                line = re.sub(r"PRIMARY KEY","PK,",line,flags=re.IGNORECASE)
                line = re.sub(r"GENERATED BY DEFAULT AS IDENTITY\s*","",line,flags=re.IGNORECASE) # Just ignore this case
                line = re.sub(r"DEFAULT '*([a-zA-Z_\(\)]+)'*",r"DEFAULT: '\1',",line,flags=re.IGNORECASE)
                line = re.sub(r"DEFAULT ([0-9]+)",r"DEFAULT: \1,",line,flags=re.IGNORECASE)
                line = re.sub(r"REFERENCES (\w+)\((\w*)\)",r"REF: - \1.\2, ",line,flags=re.IGNORECASE) # Default to 1-1
                line = re.sub(r"CHECK\s*\(.*\)",r"",line,flags=re.IGNORECASE)
                line = re.sub(r"NOT NULL",r"NOT NULL,",line,flags=re.IGNORECASE)
                line = re.sub(r"UNIQUE",r"UNIQUE,",line,flags=re.IGNORECASE)
                line = re.sub(r"\s*,\s*\]","]",line,flags=re.IGNORECASE)
                line = re.sub(r";","",line,flags=re.IGNORECASE)

                result += line
        result += "\n"
    return result


def translate_sql(files):
    if type(files) == str:
        files = [files]

    result = {}

    current_table = None

    for file in files:
        with open(file,"r") as f:
            while line := f.readline():
                if table_name := re.match(
                        r"CREATE TABLE(?: IF NOT EXISTS)? (?P<table_name>\w+)",
                        line, re.IGNORECASE
                    ):
                    result[table_name.group("table_name")] = {}
                    current_table = table_name.group("table_name")
                
                elif current_table:
                    if col := re.match(
                            r"^\s*(?P<column>[\w_]+)\s+(?P<type>[\w\(\)_]+)\s+(?P<args>.*)",
                            line, re.IGNORECASE
                        ):

                        attr = col.group("column")
                        typ = col.group("type")
                        args = col.group("args")
                        args = re.sub(r"\s*,*\s*$","",args)
                        
                        if re.findall(r"PRIMARY\s+KEY",args,re.IGNORECASE):
                            result[current_table]["pk"] = attr
                            args = re.sub(r"PRIMARY\s+KEY","",args,flags=re.IGNORECASE)

                        if not (attrs := result[current_table].get("attributes")):
                            attrs = result[current_table]["attributes"] = {}

                        attrs[attr] = {
                            "python_type": "Any",
                            "sql_type": typ,
                            "column_arguments": args
                        }

                        if "NOT NULL" in args.upper() and \
                            "DEFAULT" not in args.upper():
                            result[current_table]["attributes"][attr]["sample"] = \
                                f"[INSERT SAMPLE {col.group("column")} HERE]"  


    return json.dumps(result)




if __name__ == "__main__":
    if len(sys.argv) >= 2:
        files = []
        for file in os.listdir(sys.argv[1]):
            if ".sql" not in file: continue
            files.append(os.path.join(os.path.dirname(__file__), f"{sys.argv[1]}/{file}"))

        print(translate_sql(files))

    else:
        print(translate_diagram())
